# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ML_Paint.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_StyleTransferGUI(object):
    def setupUi(self, StyleTransferGUI):
        StyleTransferGUI.setObjectName("StyleTransferGUI")
        StyleTransferGUI.resize(1126, 756)
        self.centralwidget = QtWidgets.QWidget(StyleTransferGUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 10, 921, 681))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lbl_style = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_style.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_style.setObjectName("lbl_style")
        self.gridLayout.addWidget(self.lbl_style, 0, 0, 1, 1)
        self.pic_output = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.pic_output.setObjectName("pic_output")
        self.gridLayout.addWidget(self.pic_output, 2, 1, 1, 1)
        self.lbl_content = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_content.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_content.setObjectName("lbl_content")
        self.gridLayout.addWidget(self.lbl_content, 0, 2, 1, 1)
        self.pic_style = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.pic_style.setObjectName("pic_style")
        self.gridLayout.addWidget(self.pic_style, 1, 0, 1, 1)
        self.pic_content = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.pic_content.setObjectName("pic_content")
        self.gridLayout.addWidget(self.pic_content, 1, 2, 1, 1)
        self.lbl_output = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_output.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_output.setObjectName("lbl_output")
        self.gridLayout.addWidget(self.lbl_output, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_iter = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_iter.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_iter.setObjectName("lbl_iter")
        self.verticalLayout.addWidget(self.lbl_iter)
        self.btn_start = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout.addWidget(self.btn_start)
        self.btn_pause = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_pause.setObjectName("btn_pause")
        self.verticalLayout.addWidget(self.btn_pause)
        self.btn_save = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_save.setObjectName("btn_save")
        self.verticalLayout.addWidget(self.btn_save)
        self.gridLayout.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_style_image = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_style_image.setObjectName("lbl_style_image")
        self.verticalLayout_2.addWidget(self.lbl_style_image)
        self.edt_style = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.edt_style.setObjectName("edt_style")
        self.verticalLayout_2.addWidget(self.edt_style)
        self.lbl_content_image = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_content_image.setObjectName("lbl_content_image")
        self.verticalLayout_2.addWidget(self.lbl_content_image)
        self.edt_content = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.edt_content.setObjectName("edt_content")
        self.verticalLayout_2.addWidget(self.edt_content)
        self.lbl_output_image = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lbl_output_image.setObjectName("lbl_output_image")
        self.verticalLayout_2.addWidget(self.lbl_output_image)
        self.edt_output = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.edt_output.setObjectName("edt_output")
        self.verticalLayout_2.addWidget(self.edt_output)
        self.btn_load = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_load.setObjectName("btn_load")
        self.verticalLayout_2.addWidget(self.btn_load)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        StyleTransferGUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(StyleTransferGUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1126, 22))
        self.menubar.setObjectName("menubar")
        StyleTransferGUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(StyleTransferGUI)
        self.statusbar.setObjectName("statusbar")
        StyleTransferGUI.setStatusBar(self.statusbar)

        self.retranslateUi(StyleTransferGUI)
        QtCore.QMetaObject.connectSlotsByName(StyleTransferGUI)

    def retranslateUi(self, StyleTransferGUI):
        _translate = QtCore.QCoreApplication.translate
        StyleTransferGUI.setWindowTitle(_translate("StyleTransferGUI", "ML Paint"))
        self.lbl_style.setText(_translate("StyleTransferGUI", "Style"))
        self.lbl_content.setText(_translate("StyleTransferGUI", "Content"))
        self.lbl_output.setText(_translate("StyleTransferGUI", "Output"))
        self.lbl_iter.setText(_translate("StyleTransferGUI", "Iteration = {}"))
        self.btn_start.setText(_translate("StyleTransferGUI", "Start"))
        self.btn_pause.setText(_translate("StyleTransferGUI", "Pause"))
        self.btn_save.setText(_translate("StyleTransferGUI", "Save"))
        self.lbl_style_image.setText(_translate("StyleTransferGUI", "Style Image Name:"))
        self.lbl_content_image.setText(_translate("StyleTransferGUI", "Content Image Name:"))
        self.lbl_output_image.setText(_translate("StyleTransferGUI", "Output Image Name:"))
        self.btn_load.setText(_translate("StyleTransferGUI", "Go!"))

